DO $EF$
BEGIN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'PswdManager') THEN
CREATE SCHEMA "PswdManager";
END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS "PswdManager"."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

DO $EF$
BEGIN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'PswdManager') THEN
CREATE SCHEMA "PswdManager";
END IF;
END $EF$;

CREATE TABLE "PswdManager"."PasswordEntries" (
                                                 "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                 "Name" text NOT NULL,
                                                 "Password" text NOT NULL,
                                                 "DateAdded" timestamp with time zone NOT NULL,
                                                 "IsEmail" boolean NOT NULL,
                                                 CONSTRAINT "PK_PasswordEntries" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_PasswordEntries_Name" ON "PswdManager"."PasswordEntries" ("Name");

INSERT INTO "PswdManager"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240713192304_Initial', '8.0.7');

COMMIT;

